config/config.go
Use what will be the new topic between this service and dp-cantabular-csv-exporter.
This is required, to not interfere with dp-dataset-exporter-xlsx
Visual inspection
Anyone.
=> Use new consume topic

config/config.go, features/compose/minio.yml
As title
Visual inspect
Anyone
=> Use new minio buckets

config/config.go, handler/handler.go
Fix vault read path.
Visual inspection.
Run tests.
Anyone
=> Fix vault read path

handler/handler.go
As per title
Visual inspection.
Run tests.
Anyone
=> remove adding '.csv' as incoming filename already has it

handler/handler.go
Make vault path match what csv exporter and downloader need
Inspect code.
Run tests.
Anyone
=> Build correct vault path

config/config.go, go.mod, go.sum, handler/handler.go, handler/interface.go, handler/metadata.go, handler/mock/dataset-api-client.go, service/interfaces.go, service/mock/dataset_api_client.go
Add logic for metadata xlsx file creation
Confirm changes are correct and make sense
Anyone
=> add logic for metadata xlsx file creation

Makefile, features/compose/dp-cantabular-xlsx-exporter.yml, go.mod, go.sum
Add compiler '-race' check flag to component tests
Visually inspect changes.
Anyone.
=> Add race check to component tests

go.mod, go.sum, handler/s3_stream_writer_test.go
As per title.
Plus comment out a line of test code to stop linter whinging.
Visual inspection.
Run component tests.
Anyone.
=> Use latest kafka lib to get correct stack traces

.nancy-ignore, event/event.go, features/dp-cantabular-xlsx-exporter-private.feature, features/dp-cantabular-xlsx-exporter-published.feature, features/dp-cantabular-xlsx-exporter-unhealthy.feature, features/steps/steps.go, go.mod, go.sum, handler/handler.go, handler/metadata.go, handler/s3_stream_writer.go, schema/schema.go
US: https://trello.com/c/DLbZ4zUR/5696-issue-with-dp-cantabular-xls-exporter
- XLSX exporter needs a file name exported in CSV exporter to work on. This is now being passed in event. 
- Fixed issues around metadata exporter
Please have a look at other parallel PRs in csv  and metadata exporter to make sure that all schema and events match
Anyone
=> Fixed issues with xlsx exporter

Dockerfile.local, go.sum
Update dockerfile to use latest Reflex version
Confirm changes are correct
Anyone
=> Update dockerfile to use latest Reflex version

handler/handler.go
Previously we were applying an header informing the user about the size
of the file, i.e, below or over the 10k lines threshold.
This information was being inserted in the `A1` cell.
This has been removed.
Resolves: 5830
Sense check it and ensure tests are :green_circle: 
Any ONS developer
=> 5830 - Remove XLS header about 10k Lines

dp-cantabular-xlsx-exporter.nomad
We need to have an instance of this app running on the web subnet.
Resolve: [5872](https://trello.com/c/rzn2jjDb/5872-create-instances-of-exporter-services-in-web) 
Sense check it
Any ONS developer
=> 5872 Add web group into the nomad file

ci/scripts/component.sh, features/compose/kafka-cluster.yml, go.mod, go.sum, handler/handler.go, handler/interface.go, handler/mock/dataset-api-client.go, service/interfaces.go, service/mock/dataset_api_client.go
...and not the dataset-api/instances (which is not available in `web`)
=> if message is for a filter, use the filter-api to determine if published

config/config.go, handler/handler.go, handler/handler_test.go
Amending link for XLSX files for published datasets to fix the current prod issue.
Ensure the changes make sense and the tests pass.
Anyone.
=> Amending link for published datasets to fix prod issue

dp-cantabular-xlsx-exporter.nomad
Changes copied from csv-exporter .nomad file.
compare changes to whats in csv-exporter.nomad file
Platform team with prod access.
=> Add separate max_parallel for more than 1 deployment at a time

features/dp-cantabular-xlsx-exporter-private.feature, features/dp-cantabular-xlsx-exporter-published.feature, handler/handler.go, handler/handler_test.go
Update version with `XLSX` download instead of `XLS`
Check change makes sense
Anyone
=> Update version with XLSX file type instead of XLS

Dockerfile.concourse
As per title
Check the changed line looks correct and yo can see what it references on docker hub
Anyone
=> Update base image used in build of nomad deployed image to ubuntu-20.04

handler/handler.go
Update file name for filtered downloads
Changes make sense
Anyone
=> update file name for filtered downloads

features/dp-cantabular-xlsx-exporter-private.feature, features/dp-cantabular-xlsx-exporter-published.feature, handler/handler.go, handler/handler_test.go
Revert the changes made in these PR's - https://github.com/ONSdigital/dp-cantabular-xlsx-exporter/pull/84 & https://github.com/ONSdigital/dp-cantabular-xlsx-exporter/pull/93
Confirm the above has been done
Anyone
=> revert xls changes

handler/metadata.go
Add variable description for metadata
Confirm changes make sense
Anyone
=> add variable description for metadata

handler/metadata.go
use time.Now rather than release date for BYO metadata
check changes
Anyone
=> use time.Now rather than release date for BYO metadata

handler/metadata.go
- Release 2.11.1
- Small bugfix to remove description for byo
check correct commits
Anyone
=> omit description for byo

README.md, config/config.go, config/config_test.go, main.go
Adds a Batch Timeout environment variable and configures OpenTelemetry to use it.
=> DIS-150 OpenTelemetry Batch Timeout

ci/audit.yml, ci/build.yml, ci/component.yml, ci/lint.yml, ci/unit.yml
Use AWS ECR for CI pull request
Visual inspection
Anyone
=> Use AWS ECR for CI pull request

ci/audit.yml, ci/build.yml, ci/component.yml, ci/lint.yml, ci/unit.yml
As per title
Visual inspection (and compare to commit '89da5f43831275050e0d348b9ff5b3d45739127d' .. the files should look like whats in that commit)
Anyone.
=> Undo changes used for testing using ECR

.nancy-ignore, Dockerfile.local, Makefile, ci/audit.yml, ci/build.yml, ci/lint.yml, ci/unit.yml
- Switch to vulncheck
- bump Go version
- remove nancy.ignore
CI passes
Anyone
=> switch to vulncheck and bump go versions
